

#ifndef _FONT_H_
#define _FONT_H_

#define FONT_WIDTH  7
#define FONT_HEIGHT 8
#define FONT_SCALING 2

#define ABS_WIDTH (FONT_WIDTH*FONT_SCALING)
#define ABS_HEIGHT (FONT_HEIGHT*FONT_SCALING)
#endif